// Code generated by pggen. DO NOT EDIT.

package clickhouse_multi

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
)

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	// Sums usage per subscriber for one provider.
	SumByProvider(ctx context.Context, provider string) ([]UsageRow, error)

	// The same shape over a different filter, so the two share one Go struct.
	SumBusySubscribers(ctx context.Context, minUnits int64) ([]UsageRow, error)

	// Sums usage for one subscriber, sharing UsageRow across files.
	SumByMSISDN(ctx context.Context, msisdnA string) ([]UsageRow, error)

	// Returns the two columns whose Go types are built out of wrappers. A pointer
	// reports no import of its own and a map reports none either — its key and
	// value can come from different packages — so this file needs "time" from
	// inside a *time.Time and nothing else brings it in.
	FindEndsByMSISDN(ctx context.Context, msisdnA string) ([]FindEndsByMSISDNRow, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn // underlying ClickHouse transport to use
}

// genericConn is a connection to ClickHouse, like clickhouse.Conn or a
// decorator that wraps one.
type genericConn interface {
	// Select runs the query and scans every row into dest, a pointer to a
	// slice of structs.
	Select(ctx context.Context, dest any, query string, args ...any) error
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// a clickhouse.Conn.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

type UsageRow struct {
	MSISDNA    string     `ch:"msisdn_a"    json:"msisdn_a"`
	RecordType RecordType `ch:"record_type" json:"record_type"`
	Units      int64      `ch:"units"       json:"units"`
}

const sumByProviderSQL = `SELECT
    msisdn_a,
    any(record_type) AS record_type,
    sum(units)       AS units
FROM call_record
WHERE provider = cast(@provider AS String)
GROUP BY msisdn_a
ORDER BY msisdn_a;`

// SumByProvider implements Querier.SumByProvider.
func (q *DBQuerier) SumByProvider(ctx context.Context, provider string) ([]UsageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SumByProvider")
	var items []UsageRow
	if err := q.conn.Select(ctx, &items, sumByProviderSQL,
		clickhouse.Named("provider", provider),
	); err != nil {
		return nil, fmt.Errorf("query SumByProvider: %w", err)
	}
	return items, nil
}

const sumBusySubscribersSQL = `SELECT
    msisdn_a,
    any(record_type) AS record_type,
    sum(units)       AS units
FROM call_record
GROUP BY msisdn_a
HAVING units >= cast(@min_units AS Int64)
ORDER BY msisdn_a;`

// SumBusySubscribers implements Querier.SumBusySubscribers.
func (q *DBQuerier) SumBusySubscribers(ctx context.Context, minUnits int64) ([]UsageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SumBusySubscribers")
	var items []UsageRow
	if err := q.conn.Select(ctx, &items, sumBusySubscribersSQL,
		clickhouse.Named("min_units", minUnits),
	); err != nil {
		return nil, fmt.Errorf("query SumBusySubscribers: %w", err)
	}
	return items, nil
}
