// Code generated by pggen. DO NOT EDIT.

package clickhouse_multi

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
	"time"
)

const sumByMSISDNSQL = `SELECT
    msisdn_a,
    any(record_type) AS record_type,
    sum(units)       AS units
FROM call_record
WHERE msisdn_a = cast(@msisdn_a AS String)
GROUP BY msisdn_a;`

// SumByMSISDN implements Querier.SumByMSISDN.
func (q *DBQuerier) SumByMSISDN(ctx context.Context, msisdnA string) ([]UsageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SumByMSISDN")
	var items []UsageRow
	if err := q.conn.Select(ctx, &items, sumByMSISDNSQL,
		clickhouse.Named("msisdn_a", msisdnA),
	); err != nil {
		return nil, fmt.Errorf("query SumByMSISDN: %w", err)
	}
	return items, nil
}

const findEndsByMSISDNSQL = `SELECT
    ended_at,
    tag_sets
FROM call_record
WHERE msisdn_a = cast(@msisdn_a AS String)
ORDER BY units;`

type FindEndsByMSISDNRow struct {
	EndedAt *time.Time          `ch:"ended_at" json:"ended_at"`
	TagSets []map[string]string `ch:"tag_sets" json:"tag_sets"`
}

// FindEndsByMSISDN implements Querier.FindEndsByMSISDN.
func (q *DBQuerier) FindEndsByMSISDN(ctx context.Context, msisdnA string) ([]FindEndsByMSISDNRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindEndsByMSISDN")
	var items []FindEndsByMSISDNRow
	if err := q.conn.Select(ctx, &items, findEndsByMSISDNSQL,
		clickhouse.Named("msisdn_a", msisdnA),
	); err != nil {
		return nil, fmt.Errorf("query FindEndsByMSISDN: %w", err)
	}
	return items, nil
}
