// Code generated by pggen. DO NOT EDIT.

package clickhouse_multi

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
)

const sumByMSISDNSQL = `SELECT
    msisdn_a,
    any(record_type) AS record_type,
    sum(units)       AS units
FROM call_record
WHERE msisdn_a = cast(@msisdn_a AS String)
GROUP BY msisdn_a;`

// SumByMSISDN implements Querier.SumByMSISDN.
func (q *DBQuerier) SumByMSISDN(ctx context.Context, msisdnA string) ([]UsageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SumByMSISDN")
	var items []UsageRow
	if err := q.conn.Select(ctx, &items, sumByMSISDNSQL,
		clickhouse.Named("msisdn_a", msisdnA),
	); err != nil {
		return nil, fmt.Errorf("query SumByMSISDN: %w", err)
	}
	return items, nil
}
