// Code generated by pggen. DO NOT EDIT.

package domain

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	DomainOne(ctx context.Context) (string, error)
	// DomainOneBatch enqueues a DomainOne query into batch to be executed
	// later by the batch.
	DomainOneBatch(batch genericBatch)
	// DomainOneScan scans the result of an executed DomainOneBatch query.
	DomainOneScan(results pgx.BatchResults) (string, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...any) *pgx.QueuedQuery
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

const domainOneSQL = `SELECT '90210'::us_postal_code;`

// DomainOne implements Querier.DomainOne.
func (q *DBQuerier) DomainOne(ctx context.Context) (string, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "DomainOne")
	row := q.conn.QueryRow(ctx, domainOneSQL)
	var item string
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query DomainOne: %w", err)
	}
	return item, nil
}

// DomainOneBatch implements Querier.DomainOneBatch.
func (q *DBQuerier) DomainOneBatch(batch genericBatch) {
	batch.Queue(domainOneSQL)
}

// DomainOneScan implements Querier.DomainOneScan.
func (q *DBQuerier) DomainOneScan(results pgx.BatchResults) (string, error) {
	row := results.QueryRow()
	var item string
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan DomainOneBatch row: %w", err)
	}
	return item, nil
}
