// Code generated by pggen. DO NOT EDIT.

package clickhouse_cdr

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"strings"
	"time"
)

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	// Sums data usage per subscriber over a time window. Inputs use ClickHouse's
	// own parameter syntax, so this file also runs as-is in clickhouse-client.
	//
	// sql=FindDataUsageSQL also emits the query text as an exported constant, for
	// a caller that has to put the query inside another statement rather than run
	// it — see query.sql_test.go, which materializes it into a temporary table.
	FindDataUsage(ctx context.Context, params FindDataUsageParams) ([]FindDataUsageRow, error)

	// Returns every column, so the generated row struct covers the whole type
	// vocabulary.
	FindCDRsByProvider(ctx context.Context, provider string) ([]FindCDRsByProviderRow, error)

	// A single row.
	FindOldestStart(ctx context.Context, provider string) (time.Time, error)

	// A single column over many rows, which cannot use struct scanning.
	ListProviders(ctx context.Context) ([]string, error)

	InsertCDR(ctx context.Context, params InsertCDRParams) error

	// Two queries share one row struct through output=. The struct is declared
	// once, and chgen checks the two agree on every column before sharing it.
	FindChargesByProvider(ctx context.Context, provider string) ([]ChargeRow, error)

	// The same shape over a different filter. end_date is Nullable here too, so
	// the shared struct keeps the pointer.
	FindChargesByLabel(ctx context.Context, label string) ([]ChargeRow, error)

	// A parameter named after a ClickHouse setting. Inference sends parameters as
	// settings, so it has to rename them to describe the query; see
	// ch.RenameParams.
	ListCDRsPaged(ctx context.Context, params ListCDRsPagedParams) ([]ListCDRsPagedRow, error)

	// Reads a table chosen at run time. {cdr_source:Identifier} names a table
	// rather than carrying a value, so it cannot be bound like one: the generated
	// method substitutes it into the query text, having checked it is a plain
	// identifier. The from parameter beside it is bound the ordinary way, which is
	// the reason pggen substitutes rather than letting ClickHouse bind the
	// identifier itself — see ch.SubstituteIdentifiers.
	//
	// chgen describes this against a table named after the parameter, cdr_source,
	// which schema.sql declares.
	SumUnitsFrom(ctx context.Context, cdrSource string, from time.Time) ([]SumUnitsFromRow, error)

	PageCDRs(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn // underlying ClickHouse transport to use
}

// genericConn is a connection to ClickHouse, like clickhouse.Conn or a
// decorator that wraps one.
type genericConn interface {
	// Select runs the query and scans every row into dest, a pointer to a
	// slice of structs.
	Select(ctx context.Context, dest any, query string, args ...any) error
	Query(ctx context.Context, query string, args ...any) (driver.Rows, error)
	QueryRow(ctx context.Context, query string, args ...any) driver.Row
	Exec(ctx context.Context, query string, args ...any) error
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// a clickhouse.Conn.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// substituteIdentifiers fills each {name:Identifier} in sql with the value
// given for name.
//
// A ClickHouse Identifier parameter names a table or column, so it cannot be
// bound like a value: it has to be in the query text before the driver sees
// it. Each value must therefore be a plain identifier — a letter or underscore
// followed by letters, digits or underscores, optionally qualified by a
// database — and anything else is refused rather than quoted, so no value can
// carry SQL of its own into the query.
func substituteIdentifiers(sql string, values map[string]string) (string, error) {
	for name, value := range values {
		if err := checkIdentifier(name, value); err != nil {
			return "", err
		}
		sql = strings.ReplaceAll(sql, "{"+name+":Identifier}", value)
	}
	return sql, nil
}

// checkIdentifier reports whether value is a plain, optionally qualified
// ClickHouse identifier. param names the query parameter, for the error.
func checkIdentifier(param, value string) error {
	if value == "" {
		return fmt.Errorf("identifier parameter %s is empty", param)
	}
	for _, part := range strings.Split(value, ".") {
		if part == "" {
			return fmt.Errorf("identifier parameter %s has an empty part in %q", param, value)
		}
		for i, r := range part {
			isLetter := r == '_' || ('a' <= r && r <= 'z') || ('A' <= r && r <= 'Z')
			if isLetter || (i > 0 && '0' <= r && r <= '9') {
				continue
			}
			return fmt.Errorf("identifier parameter %s is %q, which is not a plain identifier: "+
				"a table or column name here must be letters, digits and underscores, "+
				"optionally qualified by a database", param, value)
		}
	}
	return nil
}

type CDRPageRow struct {
	ANum      string    `ch:"a_num"      json:"a_num"`
	Units     int64     `ch:"units"      json:"units"`
	StartDate time.Time `ch:"start_date" json:"start_date"`
}

type ChargeRow struct {
	ANum    string          `ch:"a_num"    json:"a_num"`
	Charge  decimal.Decimal `ch:"charge"   json:"charge"`
	LastEnd *time.Time      `ch:"last_end" json:"last_end"`
}

const FindDataUsageSQL = `SELECT
    a_num                AS msisdn,
    sum(units)           AS data_bytes,
    sum(charge)          AS total_charge,
    max(start_date)      AS last_seen
FROM cdr
WHERE a_num IN cast(@msisdns AS Array(String))
  AND start_date >= cast(@from AS DateTime)
  AND start_date < cast(@to AS DateTime)
GROUP BY a_num
ORDER BY a_num`

type FindDataUsageParams struct {
	Msisdns []string  `json:"msisdns"`
	From    time.Time `json:"from"`
	To      time.Time `json:"to"`
}

type FindDataUsageRow struct {
	Msisdn      string          `ch:"msisdn"       json:"msisdn"`
	DataBytes   int64           `ch:"data_bytes"   json:"data_bytes"`
	TotalCharge decimal.Decimal `ch:"total_charge" json:"total_charge"`
	LastSeen    time.Time       `ch:"last_seen"    json:"last_seen"`
}

// FindDataUsage implements Querier.FindDataUsage.
func (q *DBQuerier) FindDataUsage(ctx context.Context, params FindDataUsageParams) ([]FindDataUsageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindDataUsage")
	var items []FindDataUsageRow
	if err := q.conn.Select(ctx, &items, FindDataUsageSQL,
		clickhouse.Named("msisdns", params.Msisdns),
		clickhouse.Named("from", params.From),
		clickhouse.Named("to", params.To),
	); err != nil {
		return nil, fmt.Errorf("query FindDataUsage: %w", err)
	}
	return items, nil
}

const findCDRsByProviderSQL = `SELECT *
FROM cdr
WHERE provider = cast(@provider AS String)
ORDER BY a_num, start_date;`

type FindCDRsByProviderRow struct {
	ANum           string            `ch:"a_num"           json:"a_num"`
	RecordType     string            `ch:"record_type"     json:"record_type"`
	Rat            *string           `ch:"rat"             json:"rat"`
	Provider       string            `ch:"provider"        json:"provider"`
	Units          int64             `ch:"units"           json:"units"`
	Charge         decimal.Decimal   `ch:"charge"          json:"charge"`
	StartDate      time.Time         `ch:"start_date"      json:"start_date"`
	EndDate        *time.Time        `ch:"end_date"        json:"end_date"`
	UpdatedAt      time.Time         `ch:"updated_at"      json:"updated_at"`
	Labels         []string          `ch:"labels"          json:"labels"`
	Metadata       map[string]string `ch:"metadata"        json:"metadata"`
	SubscriptionID uuid.UUID         `ch:"subscription_id" json:"subscription_id"`
	CustomerID     *uuid.UUID        `ch:"customer_id"     json:"customer_id"`
	Premium        bool              `ch:"premium"         json:"premium"`
}

// FindCDRsByProvider implements Querier.FindCDRsByProvider.
func (q *DBQuerier) FindCDRsByProvider(ctx context.Context, provider string) ([]FindCDRsByProviderRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindCDRsByProvider")
	var items []FindCDRsByProviderRow
	if err := q.conn.Select(ctx, &items, findCDRsByProviderSQL,
		clickhouse.Named("provider", provider),
	); err != nil {
		return nil, fmt.Errorf("query FindCDRsByProvider: %w", err)
	}
	return items, nil
}

const findOldestStartSQL = `SELECT min(start_date) AS oldest
FROM cdr
WHERE provider = cast(@provider AS String);`

// FindOldestStart implements Querier.FindOldestStart.
func (q *DBQuerier) FindOldestStart(ctx context.Context, provider string) (time.Time, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindOldestStart")
	var item time.Time
	row := q.conn.QueryRow(ctx, findOldestStartSQL,
		clickhouse.Named("provider", provider),
	)
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query FindOldestStart: %w", err)
	}
	return item, nil
}

const listProvidersSQL = `SELECT DISTINCT provider
FROM cdr
ORDER BY provider;`

// ListProviders implements Querier.ListProviders.
func (q *DBQuerier) ListProviders(ctx context.Context) ([]string, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ListProviders")
	rows, err := q.conn.Query(ctx, listProvidersSQL)
	if err != nil {
		return nil, fmt.Errorf("query ListProviders: %w", err)
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item string
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan ListProviders row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close ListProviders rows: %w", err)
	}
	return items, nil
}

const insertCDRSQL = `INSERT INTO cdr (
    a_num, record_type, rat, provider, units, charge, start_date, end_date,
    updated_at, labels, metadata, subscription_id, customer_id, premium
)
VALUES (
    cast(@a_num AS String), cast(@record_type AS String), cast(@rat AS Nullable(String)),
    cast(@provider AS String), cast(@units AS Int64), cast(@charge AS Decimal(18, 6)),
    cast(@start_date AS DateTime), cast(@end_date AS Nullable(DateTime)),
    cast(@updated_at AS DateTime64(3)), cast(@labels AS Array(String)),
    cast(@metadata AS Map(String, String)), cast(@subscription_id AS UUID),
    cast(@customer_id AS Nullable(UUID)), cast(@premium AS Bool)
);`

type InsertCDRParams struct {
	ANum           string            `json:"a_num"`
	RecordType     string            `json:"record_type"`
	Rat            *string           `json:"rat"`
	Provider       string            `json:"provider"`
	Units          int64             `json:"units"`
	Charge         decimal.Decimal   `json:"charge"`
	StartDate      time.Time         `json:"start_date"`
	EndDate        *time.Time        `json:"end_date"`
	UpdatedAt      time.Time         `json:"updated_at"`
	Labels         []string          `json:"labels"`
	Metadata       map[string]string `json:"metadata"`
	SubscriptionID uuid.UUID         `json:"subscription_id"`
	CustomerID     *uuid.UUID        `json:"customer_id"`
	Premium        bool              `json:"premium"`
}

// InsertCDR implements Querier.InsertCDR.
func (q *DBQuerier) InsertCDR(ctx context.Context, params InsertCDRParams) error {
	ctx = context.WithValue(ctx, "pggen_query_name", "InsertCDR")
	if err := q.conn.Exec(ctx, insertCDRSQL,
		clickhouse.Named("a_num", params.ANum),
		clickhouse.Named("record_type", params.RecordType),
		clickhouse.Named("rat", params.Rat),
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("units", params.Units),
		clickhouse.Named("charge", params.Charge),
		clickhouse.Named("start_date", params.StartDate),
		clickhouse.Named("end_date", params.EndDate),
		clickhouse.Named("updated_at", params.UpdatedAt),
		clickhouse.Named("labels", params.Labels),
		clickhouse.Named("metadata", params.Metadata),
		clickhouse.Named("subscription_id", params.SubscriptionID),
		clickhouse.Named("customer_id", params.CustomerID),
		clickhouse.Named("premium", params.Premium),
	); err != nil {
		return fmt.Errorf("exec query InsertCDR: %w", err)
	}
	return nil
}

const findChargesByProviderSQL = `SELECT
    a_num,
    sum(charge) AS charge,
    max(end_date) AS last_end
FROM cdr
WHERE provider = cast(@provider AS String)
GROUP BY a_num
ORDER BY a_num;`

// FindChargesByProvider implements Querier.FindChargesByProvider.
func (q *DBQuerier) FindChargesByProvider(ctx context.Context, provider string) ([]ChargeRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindChargesByProvider")
	var items []ChargeRow
	if err := q.conn.Select(ctx, &items, findChargesByProviderSQL,
		clickhouse.Named("provider", provider),
	); err != nil {
		return nil, fmt.Errorf("query FindChargesByProvider: %w", err)
	}
	return items, nil
}

const findChargesByLabelSQL = `SELECT
    a_num,
    sum(charge) AS charge,
    max(end_date) AS last_end
FROM cdr
WHERE has(labels, cast(@label AS String))
GROUP BY a_num
ORDER BY a_num;`

// FindChargesByLabel implements Querier.FindChargesByLabel.
func (q *DBQuerier) FindChargesByLabel(ctx context.Context, label string) ([]ChargeRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindChargesByLabel")
	var items []ChargeRow
	if err := q.conn.Select(ctx, &items, findChargesByLabelSQL,
		clickhouse.Named("label", label),
	); err != nil {
		return nil, fmt.Errorf("query FindChargesByLabel: %w", err)
	}
	return items, nil
}

const listCDRsPagedSQL = `SELECT a_num, units
FROM cdr
WHERE provider = cast(@provider AS String)
ORDER BY a_num, start_date
LIMIT cast(@limit AS UInt32) OFFSET cast(@offset AS UInt32);`

type ListCDRsPagedParams struct {
	Provider string `json:"provider"`
	Limit    uint32 `json:"limit"`
	Offset   uint32 `json:"offset"`
}

type ListCDRsPagedRow struct {
	ANum  string `ch:"a_num" json:"a_num"`
	Units int64  `ch:"units" json:"units"`
}

// ListCDRsPaged implements Querier.ListCDRsPaged.
func (q *DBQuerier) ListCDRsPaged(ctx context.Context, params ListCDRsPagedParams) ([]ListCDRsPagedRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ListCDRsPaged")
	var items []ListCDRsPagedRow
	if err := q.conn.Select(ctx, &items, listCDRsPagedSQL,
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("limit", params.Limit),
		clickhouse.Named("offset", params.Offset),
	); err != nil {
		return nil, fmt.Errorf("query ListCDRsPaged: %w", err)
	}
	return items, nil
}

const sumUnitsFromSQL = `SELECT
    provider,
    sum(units) AS units
FROM {cdr_source:Identifier}
WHERE start_date >= cast(@from AS DateTime)
GROUP BY provider
ORDER BY provider;`

type SumUnitsFromRow struct {
	Provider string `ch:"provider" json:"provider"`
	Units    int64  `ch:"units"    json:"units"`
}

// SumUnitsFrom implements Querier.SumUnitsFrom.
func (q *DBQuerier) SumUnitsFrom(ctx context.Context, cdrSource string, from time.Time) ([]SumUnitsFromRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SumUnitsFrom")
	var items []SumUnitsFromRow
	sql, err := substituteIdentifiers(sumUnitsFromSQL, map[string]string{"cdr_source": cdrSource})
	if err != nil {
		return nil, fmt.Errorf("query SumUnitsFrom: %w", err)
	}
	if err := q.conn.Select(ctx, &items, sql,
		clickhouse.Named("from", from),
	); err != nil {
		return nil, fmt.Errorf("query SumUnitsFrom: %w", err)
	}
	return items, nil
}

const pageCDRsDefaultSQL = `SELECT
    a_num,
    units,
    start_date
FROM cdr
WHERE provider = cast(@provider AS String)
  AND (a_num > cast(@after_a_num AS Nullable(String))
        OR (cast(@after_a_num AS Nullable(String)) IS NULL))
ORDER BY a_num ASC
LIMIT cast(@limit AS UInt32);`

func (q *DBQuerier) pageCDRsDefault(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "PageCDRsDefault")
	var items []CDRPageRow
	if err := q.conn.Select(ctx, &items, pageCDRsDefaultSQL,
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("after_a_num", params.AfterANum),
		clickhouse.Named("limit", params.Limit),
	); err != nil {
		return nil, fmt.Errorf("query PageCDRsDefault: %w", err)
	}
	return items, nil
}

const pageCDRsStartDateDescSQL = `SELECT
    a_num,
    units,
    start_date
FROM cdr
WHERE provider = cast(@provider AS String)
  AND ((start_date, a_num) < (cast(@after_start AS Nullable(DateTime)), cast(@after_a_num AS Nullable(String)))
        OR (cast(@after_start AS Nullable(DateTime)) IS NULL AND cast(@after_a_num AS Nullable(String)) IS NULL))
ORDER BY start_date DESC, a_num DESC
LIMIT cast(@limit AS UInt32);`

func (q *DBQuerier) pageCDRsStartDateDesc(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "PageCDRsStartDateDesc")
	var items []CDRPageRow
	if err := q.conn.Select(ctx, &items, pageCDRsStartDateDescSQL,
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("after_start", params.AfterStart),
		clickhouse.Named("after_a_num", params.AfterANum),
		clickhouse.Named("limit", params.Limit),
	); err != nil {
		return nil, fmt.Errorf("query PageCDRsStartDateDesc: %w", err)
	}
	return items, nil
}

const pageCDRsStartDateAscSQL = `SELECT
    a_num,
    units,
    start_date
FROM cdr
WHERE provider = cast(@provider AS String)
  AND ((start_date, a_num) > (cast(@after_start AS Nullable(DateTime)), cast(@after_a_num AS Nullable(String)))
        OR (cast(@after_start AS Nullable(DateTime)) IS NULL AND cast(@after_a_num AS Nullable(String)) IS NULL))
ORDER BY start_date ASC, a_num ASC
LIMIT cast(@limit AS UInt32);`

func (q *DBQuerier) pageCDRsStartDateAsc(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "PageCDRsStartDateAsc")
	var items []CDRPageRow
	if err := q.conn.Select(ctx, &items, pageCDRsStartDateAscSQL,
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("after_start", params.AfterStart),
		clickhouse.Named("after_a_num", params.AfterANum),
		clickhouse.Named("limit", params.Limit),
	); err != nil {
		return nil, fmt.Errorf("query PageCDRsStartDateAsc: %w", err)
	}
	return items, nil
}

const pageCDRsUnitsDescSQL = `SELECT
    a_num,
    units,
    start_date
FROM cdr
WHERE provider = cast(@provider AS String)
  AND ((units, a_num) < (cast(@after_units AS Nullable(Int64)), cast(@after_a_num AS Nullable(String)))
        OR (cast(@after_units AS Nullable(Int64)) IS NULL AND cast(@after_a_num AS Nullable(String)) IS NULL))
ORDER BY units DESC, a_num DESC
LIMIT cast(@limit AS UInt32);`

func (q *DBQuerier) pageCDRsUnitsDesc(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "PageCDRsUnitsDesc")
	var items []CDRPageRow
	if err := q.conn.Select(ctx, &items, pageCDRsUnitsDescSQL,
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("after_units", params.AfterUnits),
		clickhouse.Named("after_a_num", params.AfterANum),
		clickhouse.Named("limit", params.Limit),
	); err != nil {
		return nil, fmt.Errorf("query PageCDRsUnitsDesc: %w", err)
	}
	return items, nil
}

const pageCDRsUnitsAscSQL = `SELECT
    a_num,
    units,
    start_date
FROM cdr
WHERE provider = cast(@provider AS String)
  AND ((units, a_num) > (cast(@after_units AS Nullable(Int64)), cast(@after_a_num AS Nullable(String)))
        OR (cast(@after_units AS Nullable(Int64)) IS NULL AND cast(@after_a_num AS Nullable(String)) IS NULL))
ORDER BY units ASC, a_num ASC
LIMIT cast(@limit AS UInt32);`

func (q *DBQuerier) pageCDRsUnitsAsc(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "PageCDRsUnitsAsc")
	var items []CDRPageRow
	if err := q.conn.Select(ctx, &items, pageCDRsUnitsAscSQL,
		clickhouse.Named("provider", params.Provider),
		clickhouse.Named("after_units", params.AfterUnits),
		clickhouse.Named("after_a_num", params.AfterANum),
		clickhouse.Named("limit", params.Limit),
	); err != nil {
		return nil, fmt.Errorf("query PageCDRsUnitsAsc: %w", err)
	}
	return items, nil
}

const (
	PageCDRsSortStartDate = "start_date"
	PageCDRsSortUnits     = "units"
)

type PageCDRsParams struct {
	Provider   string     `json:"provider"`
	AfterANum  *string    `json:"after_a_num"`
	Limit      uint32     `json:"limit"`
	AfterStart *time.Time `json:"after_start"`
	AfterUnits *int64     `json:"after_units"`
	SortKey    string     `json:"sort_key"`
	Descending bool       `json:"descending"`
}

// PageCDRs dispatches to the keyset-pagination variant matching
// params.SortKey and params.Descending.
func (q *DBQuerier) PageCDRs(ctx context.Context, params PageCDRsParams) ([]CDRPageRow, error) {
	switch {
	case params.SortKey == "":
		return q.pageCDRsDefault(ctx, params)
	case params.SortKey == PageCDRsSortStartDate && params.Descending:
		return q.pageCDRsStartDateDesc(ctx, params)
	case params.SortKey == PageCDRsSortStartDate && !params.Descending:
		return q.pageCDRsStartDateAsc(ctx, params)
	case params.SortKey == PageCDRsSortUnits && params.Descending:
		return q.pageCDRsUnitsDesc(ctx, params)
	case params.SortKey == PageCDRsSortUnits && !params.Descending:
		return q.pageCDRsUnitsAsc(ctx, params)
	default:
		return nil, fmt.Errorf("PageCDRs: unknown sort key %q", params.SortKey)
	}
}
