// Code generated by pggen. DO NOT EDIT.

package jsonb

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	FindByID(ctx context.Context, id pgtype.UUID) (FindByIDRow, error)
	// FindByIDBatch enqueues a FindByID query into batch to be executed
	// later by the batch.
	FindByIDBatch(batch genericBatch, id pgtype.UUID)
	// FindByIDScan scans the result of an executed FindByIDBatch query.
	FindByIDScan(results pgx.BatchResults) (FindByIDRow, error)

	Create(ctx context.Context, data []byte, metadata []byte) (CreateRow, error)
	// CreateBatch enqueues a Create query into batch to be executed
	// later by the batch.
	CreateBatch(batch genericBatch, data []byte, metadata []byte)
	// CreateScan scans the result of an executed CreateBatch query.
	CreateScan(results pgx.BatchResults) (CreateRow, error)

	ListAll(ctx context.Context) ([]ListAllRow, error)
	// ListAllBatch enqueues a ListAll query into batch to be executed
	// later by the batch.
	ListAllBatch(batch genericBatch)
	// ListAllScan scans the result of an executed ListAllBatch query.
	ListAllScan(results pgx.BatchResults) ([]ListAllRow, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...any) *pgx.QueuedQuery
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

const findByIDSQL = `SELECT id, data, metadata, created_at
FROM jsonb_example
WHERE id = $1;`

type FindByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Data      []byte             `json:"data"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// FindByID implements Querier.FindByID.
func (q *DBQuerier) FindByID(ctx context.Context, id pgtype.UUID) (FindByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindByID")
	row := q.conn.QueryRow(ctx, findByIDSQL, id)
	var item FindByIDRow
	if err := row.Scan(&item.ID, &item.Data, &item.Metadata, &item.CreatedAt); err != nil {
		return item, fmt.Errorf("query FindByID: %w", err)
	}
	return item, nil
}

// FindByIDBatch implements Querier.FindByIDBatch.
func (q *DBQuerier) FindByIDBatch(batch genericBatch, id pgtype.UUID) {
	batch.Queue(findByIDSQL, id)
}

// FindByIDScan implements Querier.FindByIDScan.
func (q *DBQuerier) FindByIDScan(results pgx.BatchResults) (FindByIDRow, error) {
	row := results.QueryRow()
	var item FindByIDRow
	if err := row.Scan(&item.ID, &item.Data, &item.Metadata, &item.CreatedAt); err != nil {
		return item, fmt.Errorf("scan FindByIDBatch row: %w", err)
	}
	return item, nil
}

const createSQL = `INSERT INTO jsonb_example (data, metadata)
VALUES ($1, $2)
RETURNING id, data, metadata, created_at;`

type CreateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Data      []byte             `json:"data"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Create implements Querier.Create.
func (q *DBQuerier) Create(ctx context.Context, data []byte, metadata []byte) (CreateRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "Create")
	row := q.conn.QueryRow(ctx, createSQL, data, metadata)
	var item CreateRow
	if err := row.Scan(&item.ID, &item.Data, &item.Metadata, &item.CreatedAt); err != nil {
		return item, fmt.Errorf("query Create: %w", err)
	}
	return item, nil
}

// CreateBatch implements Querier.CreateBatch.
func (q *DBQuerier) CreateBatch(batch genericBatch, data []byte, metadata []byte) {
	batch.Queue(createSQL, data, metadata)
}

// CreateScan implements Querier.CreateScan.
func (q *DBQuerier) CreateScan(results pgx.BatchResults) (CreateRow, error) {
	row := results.QueryRow()
	var item CreateRow
	if err := row.Scan(&item.ID, &item.Data, &item.Metadata, &item.CreatedAt); err != nil {
		return item, fmt.Errorf("scan CreateBatch row: %w", err)
	}
	return item, nil
}

const listAllSQL = `SELECT id, data, metadata, created_at
FROM jsonb_example
ORDER BY created_at DESC;`

type ListAllRow struct {
	ID        pgtype.UUID        `json:"id"`
	Data      []byte             `json:"data"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListAll implements Querier.ListAll.
func (q *DBQuerier) ListAll(ctx context.Context) ([]ListAllRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ListAll")
	rows, err := q.conn.Query(ctx, listAllSQL)
	if err != nil {
		return nil, fmt.Errorf("query ListAll: %w", err)
	}
	defer rows.Close()
	items := []ListAllRow{}
	for rows.Next() {
		var item ListAllRow
		if err := rows.Scan(&item.ID, &item.Data, &item.Metadata, &item.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan ListAll row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close ListAll rows: %w", err)
	}
	return items, err
}

// ListAllBatch implements Querier.ListAllBatch.
func (q *DBQuerier) ListAllBatch(batch genericBatch) {
	batch.Queue(listAllSQL)
}

// ListAllScan implements Querier.ListAllScan.
func (q *DBQuerier) ListAllScan(results pgx.BatchResults) ([]ListAllRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query ListAllBatch: %w", err)
	}
	defer rows.Close()
	items := []ListAllRow{}
	for rows.Next() {
		var item ListAllRow
		if err := rows.Scan(&item.ID, &item.Data, &item.Metadata, &item.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan ListAllBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close ListAllBatch rows: %w", err)
	}
	return items, err
}
