// Code generated by pggen. DO NOT EDIT.

package numeric_external

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5"
	"github.com/shopspring/decimal"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	InsertNumeric(ctx context.Context, num decimal.Decimal, numArr []NumericExternalType) (pgconn.CommandTag, error)
	// InsertNumericBatch enqueues a InsertNumeric query into batch to be executed
	// later by the batch.
	InsertNumericBatch(batch genericBatch, num decimal.Decimal, numArr []NumericExternalType)
	// InsertNumericScan scans the result of an executed InsertNumericBatch query.
	InsertNumericScan(results pgx.BatchResults) (pgconn.CommandTag, error)

	FindNumerics(ctx context.Context) ([]FindNumericsRow, error)
	// FindNumericsBatch enqueues a FindNumerics query into batch to be executed
	// later by the batch.
	FindNumericsBatch(batch genericBatch)
	// FindNumericsScan scans the result of an executed FindNumericsBatch query.
	FindNumericsScan(results pgx.BatchResults) ([]FindNumericsRow, error)
}

type DBQuerier struct {
	conn genericConn // underlying Postgres transport to use
}

var _ Querier = &DBQuerier{}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...any) *pgx.QueuedQuery
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// NewQuerierConfig creates a DBQuerier that implements Querier with the given
// config. conn is typically *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerierConfig(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// WithTx creates a new DBQuerier that uses the transaction to run all queries.
func (q *DBQuerier) WithTx(tx pgx.Tx) (*DBQuerier, error) {
	return &DBQuerier{conn: tx}, nil
}

// preparer is any Postgres connection transport that provides a way to prepare
// a statement, most commonly *pgx.Conn.
type preparer interface {
	Prepare(ctx context.Context, name, sql string) (sd *pgconn.StatementDescription, err error)
}

// PrepareAllQueries executes a PREPARE statement for all pggen generated SQL
// queries in querier files. Typical usage is as the AfterConnect callback
// for pgxpool.Config
//
// pgx will use the prepared statement if available. Calling PrepareAllQueries
// is an optional optimization to avoid a network round-trip the first time pgx
// runs a query if pgx statement caching is enabled.
func PrepareAllQueries(ctx context.Context, p preparer) error {
	if _, err := p.Prepare(ctx, insertNumericSQL, insertNumericSQL); err != nil {
		return fmt.Errorf("prepare query 'InsertNumeric': %w", err)
	}
	if _, err := p.Prepare(ctx, findNumericsSQL, findNumericsSQL); err != nil {
		return fmt.Errorf("prepare query 'FindNumerics': %w", err)
	}
	return nil
}

// NumericExternalType represents the Postgres composite type "numeric_external_type".
type NumericExternalType struct {
	Num decimal.Decimal `json:"num"`
}

// RegisterTypes registers custom Postgres types (composites and enums) with
// the pgx connection's TypeMap so that they can be scanned and encoded
// correctly. Call this once per connection after connecting.
//
// For pgxpool.Pool, use config.AfterConnect:
//
//	config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
//		return RegisterTypes(ctx, conn)
//	}
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	_, err := conn.LoadTypes(ctx, []string{
		"numeric_external_type",
	})
	return err
}

const insertNumericSQL = `INSERT INTO numeric_external (num, num_arr)
VALUES ($1, $2);`

// InsertNumeric implements Querier.InsertNumeric.
func (q *DBQuerier) InsertNumeric(ctx context.Context, num decimal.Decimal, numArr []NumericExternalType) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "InsertNumeric")
	cmdTag, err := q.conn.Exec(ctx, insertNumericSQL, num, numArr)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query InsertNumeric: %w", err)
	}
	return cmdTag, err
}

// InsertNumericBatch implements Querier.InsertNumericBatch.
func (q *DBQuerier) InsertNumericBatch(batch genericBatch, num decimal.Decimal, numArr []NumericExternalType) {
	batch.Queue(insertNumericSQL, num, numArr)
}

// InsertNumericScan implements Querier.InsertNumericScan.
func (q *DBQuerier) InsertNumericScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec InsertNumericBatch: %w", err)
	}
	return cmdTag, err
}

const findNumericsSQL = `SELECT num, num_arr
FROM numeric_external;`

type FindNumericsRow struct {
	Num    decimal.Decimal       `json:"num"`
	NumArr []NumericExternalType `json:"num_arr"`
}

// FindNumerics implements Querier.FindNumerics.
func (q *DBQuerier) FindNumerics(ctx context.Context) ([]FindNumericsRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindNumerics")
	rows, err := q.conn.Query(ctx, findNumericsSQL)
	if err != nil {
		return nil, fmt.Errorf("query FindNumerics: %w", err)
	}
	defer rows.Close()
	items := []FindNumericsRow{}
	for rows.Next() {
		var item FindNumericsRow
		if err := rows.Scan(&item.Num, &item.NumArr); err != nil {
			return nil, fmt.Errorf("scan FindNumerics row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindNumerics rows: %w", err)
	}
	return items, err
}

// FindNumericsBatch implements Querier.FindNumericsBatch.
func (q *DBQuerier) FindNumericsBatch(batch genericBatch) {
	batch.Queue(findNumericsSQL)
}

// FindNumericsScan implements Querier.FindNumericsScan.
func (q *DBQuerier) FindNumericsScan(results pgx.BatchResults) ([]FindNumericsRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query FindNumericsBatch: %w", err)
	}
	defer rows.Close()
	items := []FindNumericsRow{}
	for rows.Next() {
		var item FindNumericsRow
		if err := rows.Scan(&item.Num, &item.NumArr); err != nil {
			return nil, fmt.Errorf("scan FindNumericsBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close FindNumericsBatch rows: %w", err)
	}
	return items, err
}

