// Code generated by pggen. DO NOT EDIT.

package complex_params

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	ParamArrayInt(ctx context.Context, ints []int) ([]int, error)
	// ParamArrayIntBatch enqueues a ParamArrayInt query into batch to be executed
	// later by the batch.
	ParamArrayIntBatch(batch genericBatch, ints []int)
	// ParamArrayIntScan scans the result of an executed ParamArrayIntBatch query.
	ParamArrayIntScan(results pgx.BatchResults) ([]int, error)

	ParamNested1(ctx context.Context, dimensions Dimensions) (Dimensions, error)
	// ParamNested1Batch enqueues a ParamNested1 query into batch to be executed
	// later by the batch.
	ParamNested1Batch(batch genericBatch, dimensions Dimensions)
	// ParamNested1Scan scans the result of an executed ParamNested1Batch query.
	ParamNested1Scan(results pgx.BatchResults) (Dimensions, error)

	ParamNested2(ctx context.Context, image ProductImageType) (ProductImageType, error)
	// ParamNested2Batch enqueues a ParamNested2 query into batch to be executed
	// later by the batch.
	ParamNested2Batch(batch genericBatch, image ProductImageType)
	// ParamNested2Scan scans the result of an executed ParamNested2Batch query.
	ParamNested2Scan(results pgx.BatchResults) (ProductImageType, error)

	ParamNested2Array(ctx context.Context, images []ProductImageType) ([]ProductImageType, error)
	// ParamNested2ArrayBatch enqueues a ParamNested2Array query into batch to be executed
	// later by the batch.
	ParamNested2ArrayBatch(batch genericBatch, images []ProductImageType)
	// ParamNested2ArrayScan scans the result of an executed ParamNested2ArrayBatch query.
	ParamNested2ArrayScan(results pgx.BatchResults) ([]ProductImageType, error)

	ParamNested3(ctx context.Context, imageSet ProductImageSetType) (ProductImageSetType, error)
	// ParamNested3Batch enqueues a ParamNested3 query into batch to be executed
	// later by the batch.
	ParamNested3Batch(batch genericBatch, imageSet ProductImageSetType)
	// ParamNested3Scan scans the result of an executed ParamNested3Batch query.
	ParamNested3Scan(results pgx.BatchResults) (ProductImageSetType, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...any) *pgx.QueuedQuery
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// Dimensions represents the Postgres composite type "dimensions".
type Dimensions struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}

// ProductImageSetType represents the Postgres composite type "product_image_set_type".
type ProductImageSetType struct {
	Name      string             `json:"name"`
	OrigImage ProductImageType   `json:"orig_image"`
	Images    []ProductImageType `json:"images"`
}

// ProductImageType represents the Postgres composite type "product_image_type".
type ProductImageType struct {
	Source     string     `json:"source"`
	Dimensions Dimensions `json:"dimensions"`
}

// RegisterTypes registers custom Postgres types (composites and enums) with
// the pgx connection's TypeMap so that they can be scanned and encoded
// correctly. Call this once per connection after connecting.
//
// For pgxpool.Pool, use config.AfterConnect:
//
//	config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
//		return RegisterTypes(ctx, conn)
//	}
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	_, err := conn.LoadTypes(ctx, []string{
		"_int8",
		"_product_image_type",
		"dimensions",
		"product_image_set_type",
		"product_image_type",
	})
	return err
}

const paramArrayIntSQL = `SELECT $1::bigint[];`

// ParamArrayInt implements Querier.ParamArrayInt.
func (q *DBQuerier) ParamArrayInt(ctx context.Context, ints []int) ([]int, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ParamArrayInt")
	row := q.conn.QueryRow(ctx, paramArrayIntSQL, ints)
	item := []int{}
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query ParamArrayInt: %w", err)
	}
	return item, nil
}

// ParamArrayIntBatch implements Querier.ParamArrayIntBatch.
func (q *DBQuerier) ParamArrayIntBatch(batch genericBatch, ints []int) {
	batch.Queue(paramArrayIntSQL, ints)
}

// ParamArrayIntScan implements Querier.ParamArrayIntScan.
func (q *DBQuerier) ParamArrayIntScan(results pgx.BatchResults) ([]int, error) {
	row := results.QueryRow()
	item := []int{}
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan ParamArrayIntBatch row: %w", err)
	}
	return item, nil
}

const paramNested1SQL = `SELECT $1::dimensions;`

// ParamNested1 implements Querier.ParamNested1.
func (q *DBQuerier) ParamNested1(ctx context.Context, dimensions Dimensions) (Dimensions, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ParamNested1")
	row := q.conn.QueryRow(ctx, paramNested1SQL, dimensions)
	var item Dimensions
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query ParamNested1: %w", err)
	}
	return item, nil
}

// ParamNested1Batch implements Querier.ParamNested1Batch.
func (q *DBQuerier) ParamNested1Batch(batch genericBatch, dimensions Dimensions) {
	batch.Queue(paramNested1SQL, dimensions)
}

// ParamNested1Scan implements Querier.ParamNested1Scan.
func (q *DBQuerier) ParamNested1Scan(results pgx.BatchResults) (Dimensions, error) {
	row := results.QueryRow()
	var item Dimensions
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan ParamNested1Batch row: %w", err)
	}
	return item, nil
}

const paramNested2SQL = `SELECT $1::product_image_type;`

// ParamNested2 implements Querier.ParamNested2.
func (q *DBQuerier) ParamNested2(ctx context.Context, image ProductImageType) (ProductImageType, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ParamNested2")
	row := q.conn.QueryRow(ctx, paramNested2SQL, image)
	var item ProductImageType
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query ParamNested2: %w", err)
	}
	return item, nil
}

// ParamNested2Batch implements Querier.ParamNested2Batch.
func (q *DBQuerier) ParamNested2Batch(batch genericBatch, image ProductImageType) {
	batch.Queue(paramNested2SQL, image)
}

// ParamNested2Scan implements Querier.ParamNested2Scan.
func (q *DBQuerier) ParamNested2Scan(results pgx.BatchResults) (ProductImageType, error) {
	row := results.QueryRow()
	var item ProductImageType
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan ParamNested2Batch row: %w", err)
	}
	return item, nil
}

const paramNested2ArraySQL = `SELECT $1::product_image_type[];`

// ParamNested2Array implements Querier.ParamNested2Array.
func (q *DBQuerier) ParamNested2Array(ctx context.Context, images []ProductImageType) ([]ProductImageType, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ParamNested2Array")
	row := q.conn.QueryRow(ctx, paramNested2ArraySQL, images)
	item := []ProductImageType{}
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query ParamNested2Array: %w", err)
	}
	return item, nil
}

// ParamNested2ArrayBatch implements Querier.ParamNested2ArrayBatch.
func (q *DBQuerier) ParamNested2ArrayBatch(batch genericBatch, images []ProductImageType) {
	batch.Queue(paramNested2ArraySQL, images)
}

// ParamNested2ArrayScan implements Querier.ParamNested2ArrayScan.
func (q *DBQuerier) ParamNested2ArrayScan(results pgx.BatchResults) ([]ProductImageType, error) {
	row := results.QueryRow()
	item := []ProductImageType{}
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan ParamNested2ArrayBatch row: %w", err)
	}
	return item, nil
}

const paramNested3SQL = `SELECT $1::product_image_set_type;`

// ParamNested3 implements Querier.ParamNested3.
func (q *DBQuerier) ParamNested3(ctx context.Context, imageSet ProductImageSetType) (ProductImageSetType, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ParamNested3")
	row := q.conn.QueryRow(ctx, paramNested3SQL, imageSet)
	var item ProductImageSetType
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query ParamNested3: %w", err)
	}
	return item, nil
}

// ParamNested3Batch implements Querier.ParamNested3Batch.
func (q *DBQuerier) ParamNested3Batch(batch genericBatch, imageSet ProductImageSetType) {
	batch.Queue(paramNested3SQL, imageSet)
}

// ParamNested3Scan implements Querier.ParamNested3Scan.
func (q *DBQuerier) ParamNested3Scan(results pgx.BatchResults) (ProductImageSetType, error) {
	row := results.QueryRow()
	var item ProductImageSetType
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan ParamNested3Batch row: %w", err)
	}
	return item, nil
}
