// Code generated by pggen. DO NOT EDIT.

package function

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	OutParams(ctx context.Context) ([]OutParamsRow, error)
	// OutParamsBatch enqueues a OutParams query into batch to be executed
	// later by the batch.
	OutParamsBatch(batch genericBatch)
	// OutParamsScan scans the result of an executed OutParamsBatch query.
	OutParamsScan(results pgx.BatchResults) ([]OutParamsRow, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...any) *pgx.QueuedQuery
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// ListItem represents the Postgres composite type "list_item".
type ListItem struct {
	Name  *string `json:"name"`
	Color *string `json:"color"`
}

// ListStats represents the Postgres composite type "list_stats".
type ListStats struct {
	Val1 *string  `json:"val1"`
	Val2 []*int32 `json:"val2"`
}

// RegisterTypes registers custom Postgres types (composites and enums) with
// the pgx connection's TypeMap so that they can be scanned and encoded
// correctly. Call this once per connection after connecting.
//
// For pgxpool.Pool, use config.AfterConnect:
//
//	config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
//		return RegisterTypes(ctx, conn)
//	}
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	_, err := conn.LoadTypes(ctx, []string{
		"_int4",
		"_list_item",
		"list_item",
		"list_stats",
	})
	return err
}

const outParamsSQL = `SELECT * FROM out_params();`

type OutParamsRow struct {
	Items []ListItem `json:"_items"`
	Stats ListStats  `json:"_stats"`
}

// OutParams implements Querier.OutParams.
func (q *DBQuerier) OutParams(ctx context.Context) ([]OutParamsRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "OutParams")
	rows, err := q.conn.Query(ctx, outParamsSQL)
	if err != nil {
		return nil, fmt.Errorf("query OutParams: %w", err)
	}
	defer rows.Close()
	items := []OutParamsRow{}
	for rows.Next() {
		var item OutParamsRow
		if err := rows.Scan(&item.Items, &item.Stats); err != nil {
			return nil, fmt.Errorf("scan OutParams row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close OutParams rows: %w", err)
	}
	return items, err
}

// OutParamsBatch implements Querier.OutParamsBatch.
func (q *DBQuerier) OutParamsBatch(batch genericBatch) {
	batch.Queue(outParamsSQL)
}

// OutParamsScan implements Querier.OutParamsScan.
func (q *DBQuerier) OutParamsScan(results pgx.BatchResults) ([]OutParamsRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query OutParamsBatch: %w", err)
	}
	defer rows.Close()
	items := []OutParamsRow{}
	for rows.Next() {
		var item OutParamsRow
		if err := rows.Scan(&item.Items, &item.Stats); err != nil {
			return nil, fmt.Errorf("scan OutParamsBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close OutParamsBatch rows: %w", err)
	}
	return items, err
}
