// Code generated by pggen. DO NOT EDIT.

package void

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	VoidOnly(ctx context.Context) (pgconn.CommandTag, error)
	// VoidOnlyBatch enqueues a VoidOnly query into batch to be executed
	// later by the batch.
	VoidOnlyBatch(batch genericBatch)
	// VoidOnlyScan scans the result of an executed VoidOnlyBatch query.
	VoidOnlyScan(results pgx.BatchResults) (pgconn.CommandTag, error)

	VoidOnlyTwoParams(ctx context.Context, id int32) (pgconn.CommandTag, error)
	// VoidOnlyTwoParamsBatch enqueues a VoidOnlyTwoParams query into batch to be executed
	// later by the batch.
	VoidOnlyTwoParamsBatch(batch genericBatch, id int32)
	// VoidOnlyTwoParamsScan scans the result of an executed VoidOnlyTwoParamsBatch query.
	VoidOnlyTwoParamsScan(results pgx.BatchResults) (pgconn.CommandTag, error)

	VoidTwo(ctx context.Context) (string, error)
	// VoidTwoBatch enqueues a VoidTwo query into batch to be executed
	// later by the batch.
	VoidTwoBatch(batch genericBatch)
	// VoidTwoScan scans the result of an executed VoidTwoBatch query.
	VoidTwoScan(results pgx.BatchResults) (string, error)

	VoidThree(ctx context.Context) (VoidThreeRow, error)
	// VoidThreeBatch enqueues a VoidThree query into batch to be executed
	// later by the batch.
	VoidThreeBatch(batch genericBatch)
	// VoidThreeScan scans the result of an executed VoidThreeBatch query.
	VoidThreeScan(results pgx.BatchResults) (VoidThreeRow, error)

	VoidThree2(ctx context.Context) ([]string, error)
	// VoidThree2Batch enqueues a VoidThree2 query into batch to be executed
	// later by the batch.
	VoidThree2Batch(batch genericBatch)
	// VoidThree2Scan scans the result of an executed VoidThree2Batch query.
	VoidThree2Scan(results pgx.BatchResults) ([]string, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
	types *typeResolver // resolve types by name
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...interface{})
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn, types: newTypeResolver()}
}

// typeResolver looks up the pgtype.ValueTranscoder by Postgres type name.
type typeResolver struct {
	connInfo *pgtype.ConnInfo // types by Postgres type name
}

func newTypeResolver() *typeResolver {
	ci := pgtype.NewConnInfo()
	return &typeResolver{connInfo: ci}
}

// findValue find the OID, and pgtype.ValueTranscoder for a Postgres type name.
func (tr *typeResolver) findValue(name string) (uint32, pgtype.ValueTranscoder, bool) {
	typ, ok := tr.connInfo.DataTypeForName(name)
	if !ok {
		return 0, nil, false
	}
	v := pgtype.NewValue(typ.Value)
	return typ.OID, v.(pgtype.ValueTranscoder), true
}

// setValue sets the value of a ValueTranscoder to a value that should always
// work and panics if it fails.
func (tr *typeResolver) setValue(vt pgtype.ValueTranscoder, val interface{}) pgtype.ValueTranscoder {
	if err := vt.Set(val); err != nil {
		panic(fmt.Sprintf("set ValueTranscoder %T to %+v: %s", vt, val, err))
	}
	return vt
}

const voidOnlySQL = `SELECT void_fn();`

// VoidOnly implements Querier.VoidOnly.
func (q *DBQuerier) VoidOnly(ctx context.Context) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "VoidOnly")
	cmdTag, err := q.conn.Exec(ctx, voidOnlySQL)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query VoidOnly: %w", err)
	}
	return cmdTag, err
}

// VoidOnlyBatch implements Querier.VoidOnlyBatch.
func (q *DBQuerier) VoidOnlyBatch(batch genericBatch) {
	batch.Queue(voidOnlySQL)
}

// VoidOnlyScan implements Querier.VoidOnlyScan.
func (q *DBQuerier) VoidOnlyScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec VoidOnlyBatch: %w", err)
	}
	return cmdTag, err
}

const voidOnlyTwoParamsSQL = `SELECT void_fn_two_params($1, 'text');`

// VoidOnlyTwoParams implements Querier.VoidOnlyTwoParams.
func (q *DBQuerier) VoidOnlyTwoParams(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "VoidOnlyTwoParams")
	cmdTag, err := q.conn.Exec(ctx, voidOnlyTwoParamsSQL, id)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query VoidOnlyTwoParams: %w", err)
	}
	return cmdTag, err
}

// VoidOnlyTwoParamsBatch implements Querier.VoidOnlyTwoParamsBatch.
func (q *DBQuerier) VoidOnlyTwoParamsBatch(batch genericBatch, id int32) {
	batch.Queue(voidOnlyTwoParamsSQL, id)
}

// VoidOnlyTwoParamsScan implements Querier.VoidOnlyTwoParamsScan.
func (q *DBQuerier) VoidOnlyTwoParamsScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec VoidOnlyTwoParamsBatch: %w", err)
	}
	return cmdTag, err
}

const voidTwoSQL = `SELECT void_fn(), 'foo' as name;`

// VoidTwo implements Querier.VoidTwo.
func (q *DBQuerier) VoidTwo(ctx context.Context) (string, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "VoidTwo")
	row := q.conn.QueryRow(ctx, voidTwoSQL)
	var item string
	if err := row.Scan(nil, &item); err != nil {
		return item, fmt.Errorf("query VoidTwo: %w", err)
	}
	return item, nil
}

// VoidTwoBatch implements Querier.VoidTwoBatch.
func (q *DBQuerier) VoidTwoBatch(batch genericBatch) {
	batch.Queue(voidTwoSQL)
}

// VoidTwoScan implements Querier.VoidTwoScan.
func (q *DBQuerier) VoidTwoScan(results pgx.BatchResults) (string, error) {
	row := results.QueryRow()
	var item string
	if err := row.Scan(nil, &item); err != nil {
		return item, fmt.Errorf("scan VoidTwoBatch row: %w", err)
	}
	return item, nil
}

const voidThreeSQL = `SELECT void_fn(), 'foo' as foo, 'bar' as bar;`

type VoidThreeRow struct {
	Foo string `json:"foo"`
	Bar string `json:"bar"`
}

// VoidThree implements Querier.VoidThree.
func (q *DBQuerier) VoidThree(ctx context.Context) (VoidThreeRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "VoidThree")
	row := q.conn.QueryRow(ctx, voidThreeSQL)
	var item VoidThreeRow
	if err := row.Scan(nil, &item.Foo, &item.Bar); err != nil {
		return item, fmt.Errorf("query VoidThree: %w", err)
	}
	return item, nil
}

// VoidThreeBatch implements Querier.VoidThreeBatch.
func (q *DBQuerier) VoidThreeBatch(batch genericBatch) {
	batch.Queue(voidThreeSQL)
}

// VoidThreeScan implements Querier.VoidThreeScan.
func (q *DBQuerier) VoidThreeScan(results pgx.BatchResults) (VoidThreeRow, error) {
	row := results.QueryRow()
	var item VoidThreeRow
	if err := row.Scan(nil, &item.Foo, &item.Bar); err != nil {
		return item, fmt.Errorf("scan VoidThreeBatch row: %w", err)
	}
	return item, nil
}

const voidThree2SQL = `SELECT 'foo' as foo, void_fn(), void_fn();`

// VoidThree2 implements Querier.VoidThree2.
func (q *DBQuerier) VoidThree2(ctx context.Context) ([]string, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "VoidThree2")
	rows, err := q.conn.Query(ctx, voidThree2SQL)
	if err != nil {
		return nil, fmt.Errorf("query VoidThree2: %w", err)
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item string
		if err := rows.Scan(&item, nil, nil); err != nil {
			return nil, fmt.Errorf("scan VoidThree2 row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close VoidThree2 rows: %w", err)
	}
	return items, err
}

// VoidThree2Batch implements Querier.VoidThree2Batch.
func (q *DBQuerier) VoidThree2Batch(batch genericBatch) {
	batch.Queue(voidThree2SQL)
}

// VoidThree2Scan implements Querier.VoidThree2Scan.
func (q *DBQuerier) VoidThree2Scan(results pgx.BatchResults) ([]string, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query VoidThree2Batch: %w", err)
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item string
		if err := rows.Scan(&item, nil, nil); err != nil {
			return nil, fmt.Errorf("scan VoidThree2Batch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close VoidThree2Batch rows: %w", err)
	}
	return items, err
}

// textPreferrer wraps a pgtype.ValueTranscoder and sets the preferred encoding
// format to text instead binary (the default). pggen uses the text format
// when the OID is unknownOID because the binary format requires the OID.
// Typically occurs for unregistered types.
type textPreferrer struct {
	pgtype.ValueTranscoder
	typeName string
}

// PreferredParamFormat implements pgtype.ParamFormatPreferrer.
func (t textPreferrer) PreferredParamFormat() int16 { return pgtype.TextFormatCode }

func (t textPreferrer) NewTypeValue() pgtype.Value {
	return textPreferrer{ValueTranscoder: pgtype.NewValue(t.ValueTranscoder).(pgtype.ValueTranscoder), typeName: t.typeName}
}

func (t textPreferrer) TypeName() string {
	return t.typeName
}

// unknownOID means we don't know the OID for a type. This is okay for decoding
// because pgx call DecodeText or DecodeBinary without requiring the OID. For
// encoding parameters, pggen uses textPreferrer if the OID is unknown.
const unknownOID = 0
