package gotype

import "strings"

// stdPackages is every standard library package whose import path is a single
// segment, generated by `go list std | grep -v /`. They are the only import
// paths that are allowed to look like a bare package name.
var stdPackages = map[string]struct{}{
	"bufio": {}, "bytes": {}, "cmp": {}, "context": {}, "crypto": {},
	"embed": {}, "encoding": {}, "errors": {}, "expvar": {}, "flag": {},
	"fmt": {}, "hash": {}, "html": {}, "image": {}, "io": {}, "iter": {},
	"log": {}, "maps": {}, "math": {}, "mime": {}, "net": {}, "os": {},
	"path": {}, "plugin": {}, "reflect": {}, "regexp": {}, "runtime": {},
	"slices": {}, "sort": {}, "strconv": {}, "strings": {}, "structs": {},
	"sync": {}, "syscall": {}, "testing": {}, "time": {}, "unicode": {},
	"unique": {}, "unsafe": {}, "weak": {},
}

// IsImportPath reports whether pkgPath can be the path of a Go import.
//
// It catches one specific mistake: giving --go-type a type qualified by the
// short package name, like *pgtype.UUID, where the fully qualified
// *github.com/jackc/pgx/v5/pgtype.UUID is meant. pggen reads everything before
// the last dot as the package path, so the short form asks for a package named
// "pgtype", which no module provides and which fails to compile only once the
// generated file reaches the Go build.
//
// A path with a dot or a slash in it is taken at face value: a module path has
// a dot in its first segment, and a std package below the top level has a
// slash. Only a bare name is checked against the list, so a typo further along
// a real path still gets through — the goal is to catch the short form, not to
// resolve packages, which pggen cannot do without the target module.
func IsImportPath(pkgPath string) bool {
	if strings.ContainsAny(pkgPath, "./") {
		return true
	}
	_, ok := stdPackages[pkgPath]
	return ok
}
